SELECT MEMBER_ID, MEMBER_NAME, GENDER, FORMAT(DATE_OF_BIRTH, 'yyyy-MM-dd')
FROM MEMBER_PROFILE
WHERE 
    DATEPART(MONTH, DATE_OF_BIRTH) = 3
    AND
    GENDER = 'W'
    AND
    TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;