SELECT BOOK_ID, FORMAT(PUBLISHED_DATE, 'yyyy-MM-dd') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
AND CATEGORY = '인문'
ORDER BY 2 ASC

-- 위에는 날짜 형식을 지정하는 것이고
-- 아래는 단순히 문자열로 변환하는 것이다.

SELECT BOOK_ID, CONVERT(VARCHAR, PUBLISHED_DATE, 23) AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
AND CATEGORY = '인문'
ORDER BY 2 ASC

-- MS SQL에서는 기본적으로 날짜를 yyy-MM-dd 형식으로 변환하기에 CAST써도 됨.
SELECT BOOK_ID, CAST(PUBLISHED_DATE AS VARCHAR) AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = 2021
AND CATEGORY = '인문'
ORDER BY 2 ASC