-- FORMAT은 느릴 수 있음
SELECT DR_NAME, DR_ID, MCDP_CD, FORMAT(HIRE_YMD, 'yyyy-MM-dd') AS HIRE_YMD
FROM DOCTOR 
WHERE MCDP_CD IN ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC;

-- CONVERT가 대용량 데이터 처리시 더 적합
SELECT DR_NAME, DR_ID, MCDP_CD, CONVERT(VARCHAR, HIRE_YMD, 23) AS HIRE_YMD
FROM DOCTOR 
WHERE MCDP_CD IN ('CS', 'GS')
ORDER BY HIRE_YMD DESC, DR_NAME ASC;
