SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    CONVERT(VARCHAR, UGR.CREATED_DATE, 23) AS CREATED_DATE  -- 'YYYY-MM-DD' 형식 변환
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE >='2022-10-01'
AND UGB.CREATED_DATE < '2022-11-01'
ORDER BY 6, 1;

-- CONVERT하고 생각이 안났으면 아래처럼 하면 됨 CAST도 됨.
SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    CAST(UGR.CREATED_DATE AS CHAR) AS CREATED_DATE -- 'YYYY-MM-DD' 형식 변환
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE >='2022-10-01'
AND UGB.CREATED_DATE < '2022-11-01'
ORDER BY 6, 1;

-- 또는 FORMAT 쓰면 됨.
SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    FORMAT(UGR.CREATED_DATE, 'yyyy-MM-dd') AS CREATED_DATE -- 'YYYY-MM-DD' 형식 변환
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
WHERE UGB.CREATED_DATE >='2022-10-01'
AND UGB.CREATED_DATE < '2022-11-01'
ORDER BY 6, 1;