SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = '2021'
AND CATEGORY = '인문'
ORDER BY 2 ASC

-- 위에처럼 풀어도 되고 아래처럼 해도 된다.
-- 날짜 형식 지정이 필요 없다면 CAST()가 더 단순하고 빠르다.
-- 다만, 날짜 형식을 지정해야 하는 경우에는 DATE_FORMAT()을 사용하여 위에처럼 풀 것.

SELECT BOOK_ID, CAST(PUBLISHED_DATE AS CHAR) AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE) = '2021'
AND CATEGORY = '인문'
ORDER BY 2 ASC