SELECT 
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS D
WHERE (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0
OR (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
ORDER BY 1 ASC

-- 아래는 JOIN을 이용한 최적화된 쿼리

SELECT DISTINCT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE > 0
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID ASC;

-- 공통 테이블 이용하여 더욱 최적화
WITH SKILL_CTE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
    OR NAME = 'C#'
)

SELECT DISTINCT 
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILL_CTE SC ON D.SKILL_CODE & SC.CODE > 0
ORDER BY 1 ASC