SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, FORMAT(RR.REVIEW_DATE, 'yyyy-MM-dd') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW RR
ON MP.MEMBER_ID = RR.MEMBER_ID
AND MP.MEMBER_ID = (SELECT TOP 1 MEMBER_ID
                   FROM REST_REVIEW
                   GROUP BY MEMBER_ID
                   ORDER BY COUNT(REVIEW_ID) DESC)
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT;