WITH CAR_DISCOUNT AS (
    SELECT 
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE)/100 AS FEE_30DAY
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
      ON C.CAR_TYPE = D.CAR_TYPE
     AND D.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
), RENTED_CARS AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= '2022-11-01' -- DATE '2022-11-01' 이렇게 안해도 암묵적 변환 가능.
      AND START_DATE <= '2022-11-30'
)
SELECT 
    CAR_ID,
    CAR_TYPE,
    FEE_30DAY AS TOTAL_FEE
FROM CAR_DISCOUNT
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM RENTED_CARS)
  AND FEE_30DAY BETWEEN 500000 AND 1999999
ORDER BY 
    TOTAL_FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;