WITH FULL_ORDERS AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    ) AS CombinedOrders  -- MS SQL SERVER 에서는 반드시 서브쿼리에 별칭 둬야 함.
    GROUP BY FLAVOR
)
SELECT TOP 3 FLAVOR
FROM FULL_ORDERS
ORDER BY TOTAL_ORDER DESC;