WITH ITEM_CTE AS (
    SELECT 
    IT.ITEM_ID AS ITEM_ID
    FROM ITEM_INFO II
    LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
    WHERE IT.PARENT_ITEM_ID IS NOT NULL
    AND II.RARITY = 'RARE'
)
SELECT I_I.ITEM_ID, I_I.ITEM_NAME, I_I.RARITY
FROM ITEM_CTE IC
INNER JOIN ITEM_INFO I_I ON IC.ITEM_ID = I_I.ITEM_ID
ORDER BY 1 DESC;

-- 최적화된 쿼리, 결국 핵심은 JOIN 2번

SELECT
    I_2.ITEM_ID,
    I_2.ITEM_NAME,
    I_2.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO I_2 ON T.ITEM_ID = I_2.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY 1 DESC;