WITH CTE_ID AS (
    SELECT USER_ID
    FROM USER_INFO 
    WHERE YEAR(JOINED) = 2021
)
SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM CTE_ID)), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
INNER JOIN CTE_ID CI
ON OS.USER_ID = CI.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY 1, 2;