SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT 
        REST_ID,
        REST_NAME,
        FOOD_TYPE,
        FAVORITES,
        RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS ROTY
    FROM REST_INFO
) AS sub  -- MS SQL SERVER에서는 FROM 절 서브쿼리에서 반드시 별칭 지정해야 함.
WHERE ROTY = 1
ORDER BY FOOD_TYPE DESC;
