SELECT CAR_ID, FORMAT(ROUND(AVG(RENT_DURATION), 1), '0.0') AS AVERAGE_DURATION
FROM (
    SELECT HISTORY_ID, CAR_ID, (END_DATE - START_DATE + 1) AS RENT_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
GROUP BY CAR_ID
HAVING ROUND(AVG(RENT_DURATION), 1) >= 7
ORDER BY ROUND(AVG(RENT_DURATION), 1) DESC, CAR_ID DESC;