WITH CTE_HOUR AS (  -- MySQL은 RECURSIVE 붙여야 하지만, MS SQL은 필요 없으며 쓰면 문법 에러 남.
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM CTE_HOUR
    WHERE HOUR < 23
),
CTE_ANIMAL AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)
SELECT CH.HOUR, COALESCE(CA.COUNT, 0) AS COUNT
FROM CTE_HOUR CH
LEFT JOIN CTE_ANIMAL CA ON CH.HOUR = CA.HOUR
ORDER BY 1;