SELECT
    YEAR(OS.SALES_DATE),
    MONTH(OS.SALES_DATE),
    UI.GENDER AS GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS  -- DISTINCT 안 써서 첨에 틀렸음 ㅎㅎ... 그리고 주의할 것은 MS SQL 에서는 COUNT(DISTINCT 칼럼, 칼럼)과 같은 다중 칼럼은 지원하지 않음. 그때는 서브쿼리로 해결해야 함.
FROM ONLINE_SALE OS
LEFT JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY 
    YEAR(OS.SALES_DATE),
    MONTH(OS.SALES_DATE),
    UI.GENDER
ORDER BY 1, 2, 3;