SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
OR OPTIONS LIKE '%열선시트%'
OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;

-- 이외에도 아래와 같이 가능
SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE EXISTS (
    SELECT 1
    FROM STRING_SPLIT(OPTIONS, ',') AS split_options
    WHERE split_options.value IN ('통풍시트', '열선시트', '가죽시트')
)
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;

-- 대소문자 구분해야하는 경우는 COLLATE 사용
--Latin1_General_BIN: 이 콜레이션은 바이너리 비교를 수행하므로 대소문자를 구분
SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS COLLATE Latin1_General_BIN LIKE '%통풍시트%'
   OR OPTIONS COLLATE Latin1_General_BIN LIKE '%열선시트%'
   OR OPTIONS COLLATE Latin1_General_BIN LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE ASC;