-- 날짜 범위를 활용하면 DATETIME 칼럼의 인덱스를 더 효율적이게 활용 가능함
SELECT A.AUTHOR_ID, 
       A.AUTHOR_NAME, 
       B.CATEGORY, 
       SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
INNER JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE BS.SALES_DATE >= '2022-01-01' 
  AND BS.SALES_DATE < '2022-02-01'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;