-- MySQL 방식처럼 MONTH()로 추출할 수도 있고
SELECT COUNT(ID) AS FISH_COUNT, MON AS MONTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH, MONTH(TIME) AS MON
    FROM FISH_INFO 
    ) FISH_RECORD
GROUP BY MON
ORDER BY 2;

-- DATEPART()를 써서 추출할 수도 있음
SELECT COUNT(ID) AS FISH_COUNT, MON AS MONTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH, DATEPART(MONTH, TIME) AS MON
    FROM FISH_INFO 
    ) FISH_RECORD
GROUP BY MON
ORDER BY 2;

