SELECT 
    ROUTE,
    CAST(ROUND(SUM(D_BETWEEN_DIST), 1) AS VARCHAR(20)) + 'km') AS TOTAL_DISTANCE,
    CAST(ROUND(AVG(D_BETWEEN_DIST), 2) AS VARCHAR(20)) + 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY LINE, ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;