SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
LEFT JOIN BOOK B
ON B.BOOK_ID = BS.BOOK_ID
WHERE FORMAT(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;

-- 다만 위와 같이 하는 것은 비효율적임 형식을 바꾼후에 비교하기 때문
-- 따라서 년도와, 월로 나누어 AND 조건으로 비교하는 것이 효율적임
-- 아래와 같음
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
LEFT JOIN BOOK B
ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;