WITH FULL_ID AS (
    SELECT FLAVOR
    FROM FIRST_HALF
    UNION
    SELECT FLAVOR
    FROM JULY
),
FULL_JULY AS (
    SELECT FLAVOR AS FLAVOR, SUM(TOTAL_ORDER) AS TOTO
    FROM JULY
    GROUP BY FLAVOR
    )
SELECT FI.FLAVOR
FROM FULL_ID FI
LEFT JOIN (SELECT FLAVOR, TOTAL_ORDER AS FH_ORDER FROM FIRST_HALF) FH
ON FI.FLAVOR = FH.FLAVOR
LEFT JOIN (SELECT FLAVOR, TOTO AS J_ORDER FROM FULL_JULY) J
ON FI.FLAVOR = J.FLAVOR
ORDER BY (COALESCE(FH.FH_ORDER, 0) + COALESCE(J.J_ORDER, 0)) DESC
FETCH FIRST 3 ROWS ONLY;

-- 더 간단한 쿼리... 아 ;; 이렇게 하면 되는구나...

WITH FULL_ORDERS AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    )
    GROUP BY FLAVOR
)
SELECT FLAVOR
FROM FULL_ORDERS
ORDER BY TOTAL_ORDER DESC
FETCH FIRST 3 ROWS ONLY;