WITH TF AS (
    SELECT CC.CAR_ID AS CAR_ID, 
           CC.CAR_TYPE AS CAR_TYPE,
            (CC.DAILY_FEE*30*(100-CP.DISCOUNT_RATE)/100) AS TOTAL_FEE
    FROM CAR_RENTAL_COMPANY_CAR CC
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CP
    ON CC.CAR_TYPE = CP.CAR_TYPE
    WHERE (CP.DURATION_TYPE = '30일 이상')
    AND ((CC.CAR_TYPE = '세단') OR (CC.CAR_TYPE = 'SUV'))
),
RT AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
    AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
)
SELECT DISTINCT TF.CAR_ID, TF.CAR_TYPE, TF.TOTAL_FEE
FROM TF
WHERE TF.CAR_ID NOT IN (SELECT CAR_ID FROM RT)
AND (TF.TOTAL_FEE >= 500000 AND TF.TOTAL_FEE < 2000000)
ORDER BY TF.TOTAL_FEE DESC, TF.CAR_TYPE, TF.CAR_ID DESC;


-- 위에 처럼 해도 되는데, 아래와 같은 방식이 더 깔끔! DATE랑 BETWEEN 잘 쓰자!

WITH CAR_DISCOUNT AS (
    SELECT 
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE)/100 AS FEE_30DAY
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
      ON C.CAR_TYPE = D.CAR_TYPE
     AND D.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
), RENTED_CARS AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >= DATE '2022-11-01'
      AND START_DATE <= DATE '2022-11-30'
)
SELECT 
    CAR_ID,
    CAR_TYPE,
    FEE_30DAY AS TOTAL_FEE
FROM CAR_DISCOUNT
WHERE CAR_ID NOT IN (SELECT CAR_ID FROM RENTED_CARS)
  AND FEE_30DAY BETWEEN 500000 AND 1999999
ORDER BY 
    TOTAL_FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;