SELECT 
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR, 
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT UI.USER_ID)
                             FROM USER_INFO UI
                             WHERE EXTRACT(YEAR FROM UI.JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT DISTINCT USER_ID FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021)
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY 1, 2;


-- 위에 쿼리 최적화, CTE랑 JOIN 활용
WITH CTE_ID AS (
    SELECT USER_ID
    FROM USER_INFO 
    WHERE EXTRACT(YEAR FROM JOINED) = 2021
)
SELECT 
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR, 
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND((COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM CTE_ID)), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
INNER JOIN CTE_ID CI
ON OS.USER_ID = CI.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
ORDER BY 1, 2;