SELECT
    ED_c.ID AS ID,
    ED_c.GENOTYPE AS GENOTYPE,
    ED_p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED_c
INNER JOIN ECOLI_DATA ED_p ON ED_c.PARENT_ID = ED_p.ID
WHERE BITAND(ED_c.GENOTYPE, ED_p.GENOTYPE) = ED_p.GENOTYPE
ORDER BY 1 ASC