-- 비트연산 활용
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES S
INNER JOIN DEVELOPERS D
ON BITAND(S.CODE, D.SKILL_CODE) = S.CODE
WHERE S.CATEGORY = 'Front End'
ORDER BY 1 ASC;

-- 조인 순서 변경해서 대상을 줄여보자
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM (
    SELECT CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'
) S
INNER JOIN DEVELOPERS D
ON BITAND(S.CODE, D.SKILL_CODE) = S.CODE
ORDER BY D.ID ASC;