-- 첫 번째 쿼리: 서브쿼리 사용
SELECT 
    ID,
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS D
WHERE BITAND(D.SKILL_CODE, (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0
OR BITAND(D.SKILL_CODE, (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
ORDER BY 1 ASC;

-- 두 번째 쿼리: JOIN을 이용한 최적화
SELECT DISTINCT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S ON BITAND(D.SKILL_CODE, S.CODE) > 0
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID ASC;

-- 세 번째 쿼리: WITH 절(공통 테이블 표현식) 사용
WITH SKILL_CTE AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
    OR NAME = 'C#'
)

SELECT DISTINCT 
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILL_CTE SC ON BITAND(D.SKILL_CODE, SC.CODE) > 0
ORDER BY 1 ASC;