WITH CANT_AVAI AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE '2022-10-16' <= END_DATE
    AND DATE '2022-10-16' >= START_DATE
    GROUP BY CAR_ID
),
CAR_ID_LIST AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT CAR_ID,
    CASE
        WHEN CAR_ID NOT IN (SELECT CAR_ID FROM CANT_AVAI) THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_ID_LIST
ORDER BY CAR_ID DESC

-- 더 나은 쿼리

SELECT c.CAR_ID,
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
            WHERE h.CAR_ID = c.CAR_ID
            AND DATE '2022-10-16' BETWEEN h.START_DATE AND h.END_DATE
        ) THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) c
ORDER BY c.CAR_ID DESC;