-- MySQL과 다르게 EXTRACT(년,월,일 FROM ~)을 해야함.
-- MySQL의 경우 그냥 MONTH() YEAR() 했으면 되는데 여긴 아님.
SELECT COUNT(ID) AS FISH_COUNT, MON AS MONTH
FROM (
    SELECT ID, FISH_TYPE, LENGTH, EXTRACT(MONTH FROM TIME) AS MON
    FROM FISH_INFO 
    ) FISH_RECORD
GROUP BY MON
ORDER BY 2;