WITH SIZE_CTE AS (
    SELECT 
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
)
SELECT
    ED.YEAR,
    (SC.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID AS ID
FROM (
    SELECT
        EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
        ID,
        SIZE_OF_COLONY
    FROM ECOLI_DATA
) ED
LEFT JOIN SIZE_CTE SC ON ED.YEAR = SC.YEAR
ORDER BY 1, 2