SELECT
    YEAR(OS.SALES_DATE),
    MONTH(OS.SALES_DATE),
    UI.GENDER AS GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS  -- DISTINCT 안 써서 첨에 틀렸음 ㅎㅎ...
FROM ONLINE_SALE OS
LEFT JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY 
    YEAR(OS.SALES_DATE),
    MONTH(OS.SALES_DATE),
    UI.GENDER
ORDER BY 1, 2, 3;