SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'yyyy-MM-dd')
FROM MEMBER_PROFILE
WHERE 
    EXTRACT(MONTH FROM DATE_OF_BIRTH) = 3
    AND
    GENDER = 'W'
    AND
    TLNO IS NOT NULL
ORDER BY MEMBER_ID ASC;