SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY 
WHERE SUBSTR(ADDRESS, 1, 3) = '강원도'
ORDER BY 1

-- 아래 쿼리는 INDEX 사용시 최적화가 가능함. 위에보다 빠름
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY 
WHERE ADDRESS LIKE '강원도%'
ORDER BY 1