SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
WHERE II.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL) -- NULL이 껴있는 경우 NOT IN 은 무조건 FALSE를 내뱉음
ORDER BY 1 DESC;

-- NOT EXISTS 활요한 방법 NOT IN 보다 효율적!
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
WHERE NOT EXISTS (
    SELECT 1
    FROM ITEM_TREE IT 
    WHERE IT.PARENT_ITEM_ID = II.ITEM_ID 
    )
ORDER BY 1 DESC;

-- 카테시안 조인 사용하면 대용량 데이터에서 더 효율적이게 됨.
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
LEFT JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
WHERE IT.PARENT_ITEM_ID IS NULL
ORDER BY 1 DESC;